# Generated by Django 5.1.1 on 2024-12-15 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_wishlist_friends_alter_wishlist_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color_scheme',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 16, 55, 46, 507768)),
        ),
    ]
